---
metadata_path: /Users/ssola/Workspace/metadata/sql/
projects:
  impala_project:
      name: imapala
      backend: hive
      repo: git@github.com:ssola/test-data.git
      filters:
        only_sql_files:
          filter: file_type
          types:
            - ".sql"